### ISSUE TITLE
Cannot read property value

### ISSUE THREAD

**Issue by jerryrehy** [dnafication/saz2jmx#2]
C:\Users\j.rehak\node_modules\saz2jmx\lib\jmx.js:73
    )[0].value;
        ^

TypeError: Cannot read property 'value' of undefined
    at JMX._createHeader (C:\Users\j.rehak\node_modules\saz2jmx\lib\jmx.js:73:9)
    at JMX.addNewHTTPSampler (C:\Users\j.rehak\node_modules\saz2jmx\lib\jmx.js:215:32)
    at C:\Users\j.rehak\node_modules\saz2jmx\lib\index.js:29:13
    at Array.forEach (<anonymous>)
    at C:\Users\j.rehak\node_modules\saz2jmx\lib\index.js:28:8
    at ZipFile.<anonymous> (C:\Users\j.rehak\node_modules\saz2js\lib\index.js:152:7)
    at ZipFile.emit (events.js:210:5)
    at FdSlicer.<anonymous> (C:\Users\j.rehak\node_modules\yauzl\index.js:202:10)
    at Object.onceWrapper (events.js:299:28)
    at FdSlicer.emit (events.js:210:5)

**Comment by dnafication** [comment]
@jerryrehy sorry about the late reply. Do you have any sample saz file for which this issue is appearing?
I might've forgot to mention. I have tested this with only 'Fiddler 4', if they've made some change in the data structure in the later versions, the tool may break.

**Comment by sheldonbotha1979** [comment]
Hi @dnafication , I have the exact same error running v1.20 with a SAZ saved from Fiddler 4 v5.0.20202.18177 

I have attached a SAZ example export (inside the ZIP file) that gives the exact same error as the original poster.

[test.zip](https://github.com/dnafication/saz2jmx/files/5158710/test.zip)

I hope this is of help.

**Comment by dnafication** [comment]
Thanks for reporting. I will have a look. Didn't know anyone used this library 😄

**Comment by dnafication** [comment]
Hi @sheldonbotha1979 
this has been fixed and released a patch 1.2.1

Install it by running 
```
npm i saz2jmx@1.2.1
```

**Comment by sheldonbotha1979** [comment]
@dnafication thank you very much!

**Comment by dnafication** [comment]
The issue was due to saz file including all the `CONNECT` requests. if you clean up the saz file in fiddler before running it through, this error wont arise I believe. Also, now you will need to clean the jmx file instead ;)
